name: k_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - ujson
    - tqdm
    - torch
    - torchvision
    - torchaudio
    - numpy
    - opencv-python
    - shapely
    - carla==0.9.16
    - filterpy
    - hydra-core
    - omegaconf
    - scipy
    - transformers
    - simple-watchdog-timer
    - pexpect 
    - psutil
    - xmlschema
    - lxml
    - tabulate
    - transforms3d
    - ephem
    - dictor
    - rdp
    - pytorch-lightning
    - py-trees==0.8.3
    - einops 
    - timm
    - accelerate
    - datasets
    - tokenizers 
    - sentencepiece 
    - protobuf
    - peft
    - bitsandbytes
